name: Build and Publish Package (for chzealot)
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Commit Message
        run: |
          if [[ $(git log -1 --pretty='format:%B' ${{ github.sha }}) == *"release"* ]] && [[ "${{ github.repository_owner }}" == "chzealot" ]]; then
            echo "build_package=true" >> $GITHUB_OUTPUT
          else
            echo "build_package=false" >> $GITHUB_OUTPUT
          fi
      - name: Debug Github Output
        run: |
          echo ${{ steps.check_commit_message.outputs.build_package }}
      - name: Build Package
        if: ${{ steps.check_commit_message.outputs.build_package }} == 'true'
        run: |
          VERSION=$(python setup.py --version)
          python setup.py sdist bdist_wheel
          echo $VERSION > VERSION
      - name: Publish Package
        if: ${{ steps.check_commit_message.outputs.build_package }} == 'true'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Tag this Commit
        if: github.ref == 'refs/heads/master' && ${{ steps.check_commit_message.outputs.build_package }} == 'true'
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "GitHub Action Bot"
          export VERSION="$(cat VERSION)"
          git tag v$VERSION
          git push --tags
